/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2.1.0.27.2
    Soft IP Version: 1.1.0
    Tue Aug 18 13:51:11 2020
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module oscillator (hf_out_en_i, hf_clk_out_o, lf_clk_out_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  hf_out_en_i;
    output  hf_clk_out_o;
    output  lf_clk_out_o;
endmodule